# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    assignees:
      - "wvankuipers"
    groups:
      frontend-npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    assignees:
      - "wvankuipers"
    groups:
      backend-docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    assignees:
      - "wvankuipers"
    groups:
      frontend-docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "deploy"
    assignees:
      - "wvankuipers"
    groups:
      deploy-docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    assignees:
      - "wvankuipers"
    groups:
      backend-pip:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "wvankuipers"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
