# Generated by Django 5.1.15 on 2026-06-15 06:40

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('next_run_seq', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.suite')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('fuzz_level', models.CharField(default='30%', max_length=10)),
                ('highlight_colour', models.CharField(default='ff0000', max_length=6)),
                ('crop_area', models.CharField(blank=True, max_length=64, null=True)),
                ('diff', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=512)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to=core.models.test_screenshot_path)),
                ('screenshot_baseline', models.FileField(blank=True, null=True, upload_to=core.models.test_baseline_path)),
                ('screenshot_diff', models.FileField(blank=True, null=True, upload_to=core.models.test_diff_path)),
                ('screenshot_thumb', models.FileField(blank=True, null=True, upload_to=core.models.test_screenshot_thumb_path)),
                ('screenshot_baseline_thumb', models.FileField(blank=True, null=True, upload_to=core.models.test_baseline_thumb_path)),
                ('screenshot_diff_thumb', models.FileField(blank=True, null=True, upload_to=core.models.test_diff_thumb_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.run')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to=core.models.baseline_screenshot_path)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=core.models.baseline_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='core.suite')),
                ('test', models.ForeignKey(blank=True, help_text='Test that produced this baseline; informational only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.test')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='suite',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_suite_slug_per_project'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('suite', 'sequential_id'), name='unique_run_seq_per_suite'),
        ),
    ]
