# Generated by Django 5.1.15 on 2026-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drop_test_string_nullability'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.RunSQL(
            sql="UPDATE core_test SET status = 'done' WHERE status = 'pending'",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='test',
            name='is_new_baseline',
            field=models.BooleanField(
                default=None,
                help_text=(
                    'None = processing not yet complete; True = this submission '
                    'established a new baseline; False = baseline already existed.'
                ),
                null=True,
            ),
        ),
    ]
