# Generated by Django 6.0.8 on 2026-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_status_to_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='original_passed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
