# Generated by Django 6.0.8 on 2026-08-28 08:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_test_original_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='screenshot',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to=core.models.baseline_screenshot_path),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to=core.models.baseline_thumbnail_path),
        ),
    ]
