# Generated by Django 6.0.8 on 2026-09-01 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_baseline_screenshot_alter_baseline_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingQueueTest",
            fields=[],
            options={
                "verbose_name": "Processing queue",
                "verbose_name_plural": "Processing queue",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.test",),
        ),
    ]
