# Generated by Django 6.0.8 on 2026-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_processingqueuetest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status', 'created_at'], name='core_test_status_created_idx'),
        ),
    ]
