# Generated by Django 6.0.8 on 2026-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_test_core_test_status_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='process_attempts',
            field=models.IntegerField(default=0, help_text='Incremented each time process_test starts running this test. Used to cap redelivery attempts after a worker-crash requeue, so a screenshot that reliably crashes the worker fails permanently instead of looping forever.'),
        ),
    ]
