# Generated by Django 6.0.8 on 2026-09-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_test_process_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="processing_claim",
            field=models.IntegerField(
                default=0,
                help_text="Fencing token bumped each time a NEW process_test invocation is deliberately enqueued (initial creation, or a manual admin restart) — NOT on an automatic worker-crash redelivery of the same message, which carries the same token. process_test rejects a delivery whose token doesn't match the row's current value, so a stale/superseded attempt can't clobber a result produced by a newer one.",
            ),
        ),
    ]
